os: linux  
node_js: node  
language: node_js 
dist: focal
script:
- ruby -e 'puts ENV["MY_ENV"] || "Hello, World!"'
- rvm list
cache:  
directories:  
  - node_modules  
group: stable
addons:  
  deploy:  
    - provider: pages
    strategy: git  
    skip_cleanup: true  
    local_dir: ".pages"  
    target_branch: main
    token: "$GITHUB_TOKEN"  
    url: github.com
    'on':
      branch:
      - main
      - deploy
