deploy:
  provider: pages:git
  token: "$GITHUB_TOKEN"
  verbose: true
  cleanup: false
  keep_history: true
  url: github.com
  local_dir: pages/
  edge: true
  on:
    branch:
    - main
    - deploy
