os: linux  
node_js: node  
language: node_js 
dist: focal
script:
- ruby -e 'puts ENV["MY_ENV"] || "Hello, World!"'
- rvm list
cache:  
directories:  
  - node_modules  
group: stable
job:
  include:
    dist: focal
    deploy:
      edge: true
      provider: pages:git
      token: "$GITHUB_TOKEN"
      verbose: true
      cleanup: false
      keep_history: true
      url: github.com
      local_dir: pages/
      edge: true
      on:
        branch:
        - main
        - deploy
