dist: focal
language: ruby
script:
- ruby -e 'puts ENV["MY_ENV"] || "Hello, World!"'

deploy:
  edge: true
  provider: pages:git
  token: "$GITHUB_TOKEN"
  verbose: true
  cleanup: false
  keep_history: true
  url: github.com
  local_dir: pages/
  edge: true
  on:
    branch:
    - main
    - deploy
